name: Compile all apps
on: [push, pull_request]

jobs:
  test_applications:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/esl-epfl/x-heep-toolchain:latest
    name: Compiles all apps with gcc and clang. All must compile successfully.
    steps:
      - name: Checkout the pushed code. 
        uses: actions/checkout@v3        

      - name: Detect RISCV toolchain and export
        run: |
          tool=$(command -v riscv32-unknown-elf-gcc || true)
          if [ -z "$tool" ]; then echo "RISC-V toolchain not found"; exit 1; fi
          root=$(dirname "$(dirname "$tool")")
          echo "RISCV_XHEEP=$root" >> $GITHUB_ENV
          echo "PATH=$root/bin:$PATH" >> $GITHUB_ENV

      - name: Configure the job container and compile all apps.
        run: |
          conda init bash
          source /root/.bashrc
          conda activate core-v-mini-mcu
          make clean-all
          sed 's/is_included: "no"/is_included: "yes"/' -i configs/ci.hjson
          sed 's/num_channels:   0x1/num_channels:   0x4/' -i configs/ci.hjson
          sed 's/num_channels_per_master_port: 0x1/num_channels_per_master_port: 0x4/' -i configs/ci.hjson
          make mcu-gen X_HEEP_CFG=configs/ci.hjson
          python3 test/test_apps/test_apps.py --compile-only
